language: generic

cache:
  directories:
    - $HOME/.cargo
    - server/target

matrix:
  include:

    - os: linux
      sudo: required
      services:
        - docker
      env:
        # PUSH_IMAGES
        secure: "rcpHZYCdVCGjmlz6RlPSIjON2CXH4g1FH/51Hb+dUA5z/3cnLCi2OvqQJ3rxqgypjg/AjoIjRAgkaZ8yMlW0MpsNlL0NboSd8nDPxDWj9jFbaZTeB/a/LP1LetK0GI/8QyAHh2TaFUBaHbljBSv5ueHt2Fajl/N059jH0hwCkDyM9gxg9PGh1KpbSTeuTNgUrmUpOxRZc8Wh6HN0FyovfO52VGuhl9lJqio/6QHv2PykU/ywlLSG9cccnNdYqIUNmHr00dFUwM8KRwA+dj2lPpR6im+c5k61TdatjVrbiL+UWonyBFNavFFqUXb3oODKk2mYb6ZsJatNF/y6gVeNjPJj6SWvKWCpyM3LgUw+GNK6UcnMEml0Xkb7+5yxtuI5+CaGs4BrU0avINWuiPE7Sm28CacNwmcY05RLjO0plH238yxjCxfVFTycPPSKFqu8261xWYPHvoIRA8F18U+J4CF+EHqeymLcaA/S6dMKiAMY5EMt9EYedP0cPR+qG1bMbp6l+2CjCC0kU9QW6hTYNp0xGEO9DFxPoYuYKW5ikSiqbfhyI+M0/YUg79VL47LPBEktM2OHUzN/znQeeV0PWVKVLYpfR6uNjvUj39YQ1mwJiRKy+5lyjDWnzPQ4BoOxOyq5plI7QtXd5NnkmGywMZX4A+EsvhRJfuxgkXtsxok="
      script:
        - "./bin/dev ci"

