language: generic

cache:
  directories:
    - $HOME/.cargo
    - server/target

matrix:
  include:

    - os: linux
      sudo: required
      services:
        - docker
      env:
        # PUSH_IMAGES
        secure: "fKVy2NE5nahO5pHzaxbPwDN+pf5gatyvXgLB4D6qp2d6U1Vi5bBqA/X076Lh9Y5xq9yXuJp5Gz7+Ai8li55QndCQl5Bfjqrif3JeXwppCGrWpHPpEBr8rtAVUUQQAx5vKMPwajNjn1l+imOruWInRPUJ3EqUKR4dtaQRaI7bDATIr+QXf7TNOJClFqxN3A7JQIR5VEn0T0cLt+QX9355/6pdUx/fgW3xWpve0azfKzSAMAt1egdtqEx4w0eXiYsl0xa1GMxX7MEX98aBu5UoN/Ws2s94gtfVCOGY3Ae4ApycXiteBSd5fFL5bfWWWzW2ze+biqOlVmFcNU+KJT5hfWCEL/bGgxOJIL8O/fwzmk3B5tYzU3zoi9hbD4NELLTbOQdY79ZyqhjIVKDpPigN/Pw+QpEZqFnIGjmHMsZtAk4e+96/pmKrhIJKIDLZNbZPVS7JzsPs+mBOjZuVFTtwIVfiybQdDlaydwKV2B/Tpbz9Sn38SMs3WH3JXUo6pF46uWdw4r7QoHBnYnkFjOv8/4YfucPMUpb8uN0BZRS6YgX6TP6nI+dIpG6XXCJE/v041YL5tVLLnNsKHum6vTpy7r2qMVG1oJoKVkP9oCQkh3YGpOJC/TZoYGz3SZzP//CBZkwNCRoAaZ/rqGth91Y2QpJ8pUF/OXv6bOU1Ebtd99Y="
      script:
        - "./bin/dev ci"

