language: generic

cache:
  directories:
    - $HOME/.cargo
    - server/target

matrix:
  include:

    - os: linux
      sudo: required
      services:
        - docker
      env:
        # PUSH_IMAGES
        secure: "ZYGfp5oAoR/JUwQ2Zje33/dzkoCUog2KYqk5gCegfrThopAFyCdZEgLTc0Uy1vjC47ghL0t6KCUe9uuqh/xdbHQI4akHOpnh4/Os6lxizfdXkplaNNOUd841oUawG5C1AXULNoxkCM4BV7uUGJqn8GGbSdLB4SgrOk4Nv05BTg7B2rwtOs+FlSp7m6YcHaFNHjvEPdkXHOCfPgqxi7CxTxe8xmUGk8gjoikbBqCzDnp+kHFED35KIIbSQnRqokLl8t9IaTTgOH6QN8pQmX3QK8Lbr9BKd4FmDwNSUdbk+dyoC2FOA/QvG7tVgWIs7+obeMq8zqxSTtxbRlKGArmZQFOmaHScvpOZiBBvqNstB0QjiyGVXM6GD0YQIdU1grwQ1E915QsSZUcdEGUThpKx4KHpY4wIIHr/iITR8/bSg8sKZ+CbRVD7Xj/eosx+/cG/lvUjZG/K0yG0PqVgamlbLXveMz6L0tYmK8PxJ0bFz0IfICf+j2XkUWzmbPEPVLWfDCA8V9IOvx/741J9XMTkLD7oQV3gGp+5BQl3ToaYr4vZCpI5IdkJYwkqhVoq0JiHWfKJSt2xJAF8xfgwQbeKKokwuxFIUD/SvwvURtTS07vcHDHmfJAxWIVbg+j00q2dDVm0k+pe4o49lN53ggnbU25gp8GpWbOO4mDnBp26Kos="
      script:
        - "./bin/dev ci"

